### ISSUE TITLE
CHAT2CAlite should convert mi➶d -----> mi:̲d

### ISSUE THREAD

**Issue by saulalbert** [saulalbert/unixclan#13]
CHAT doesn't have a way to show mid-utterance intonation shifts, CA uses a colon followed by a U+0332 (combining low line) character:

We'll use a new a unicode character (U+27B6 : BLACK-FEATHERED NORTH EAST ARROW) which CHECK doesn't seem to complain about, so:

`mi➶d ------> mi:̲d`

**Comment by saulalbert** [comment]
the rising arrow is unicode: U+2197

**Comment by mumair01** [comment]
The two unicode values are for different kinds of arrows. Which one have we decided to use for CHAT?

**Comment by saulalbert** [comment]
Right - CHAT has different arrows for the ends of turns. For mid-turn intonation shifts we want to use (U+27B6 : BLACK-FEATHERED NORTH EAST ARROW) - for upward shifts and (U+27B4 BLACK-FEATHERED SOUTH EAST ARROW) - for downward shifts. This is because CHECK complains if we use end-of-turn arrows in mid-turn or mid-word, but not with the feathered variety.

**Comment by mumair01** [comment]
Oh that part I understand. My question is that you gave the unicode (U+2197), which represents the rising arrow, and the unicode (U+27B6), which represents the feathered arrow. For this issue, mid utterance intonation shift, which of those arrows are we using?

**Comment by saulalbert** [comment]
Whoops - sorry. We want to use U+27B6 - feathered arrows. I should have deleted the rising arrow comment when I edited the main task! I'll delete it now.
