### ISSUE TITLE
Replace matched ∆up triangles∆ in CHAT with >inward facing carats<  in CA 

### ISSUE THREAD

**Issue by saulalbert** [saulalbert/unixclan#4]
In CA transcription >inward facing carats< indicate faster talk. 

In CHAT fast talk is represented with:

up triangle | ∆ | ∆faster∆ | 2206

So when you find a triangle delimiter, replace it with inward facing >carats<.

NB: in CA we also have >>double inward facing carats<< for very fast talk, this might cause some issues with double up triangles when we get to calite2chat - but we're not there yet!

**Comment by mumair01** [comment]
The existing src code already implements a way to resolve this issue.

**Comment by saulalbert** [comment]
Good - closing.
