### ISSUE TITLE
Replace matched ∇down triangles∇ in CHAT with <outward facing carats>  in CA-lite 

### ISSUE THREAD

**Issue by saulalbert** [saulalbert/unixclan#5]
In CA transcription <outward facing carats> indicate slower talk.

In CHAT slow talk is represented with:

down triangle | ∇ | ∇slower∇ | left arrow | 2207

So when you find a down triangle delimiter, replace it with outward facing <carats>.

NB: in CA we also have <<double outward facing carats>> for very slow talk, so this might cause some issues with double down triangles when we get to calite2chat - but we're not there yet!

**Comment by mumair01** [comment]
This is also implemented in the original src code.

**Comment by saulalbert** [comment]
Aha! Good spot. Closing the issue - I'll add some new ones!
