### ISSUE TITLE
Replace matched  ☺smiley voice ☺  with matched £ signs 

### ISSUE THREAD

**Issue by saulalbert** [saulalbert/unixclan#6]
In CHAT we use smiley delimiters for 'smile voice', but in CA it's standard to use £ signs.

So we need to replace these:

smiley | ☺ | ☺smile voice☺ | l | 263A

With these £

**Comment by mumair01** [comment]
Would you mind telling me whether this is the standard pound symbol (u+00A3) or the fullwidth pound symbol (u+FFE1)?

**Comment by saulalbert** [comment]
The standard one. When we're converting in the other direction it'd be good to test for both but from CHAT->CA-lite we can go with u+00A3
