### ISSUE TITLE
Convert [^ comments] into ((comments))

### ISSUE THREAD

**Issue by saulalbert** [saulalbert/unixclan#7]
In CHAT, transcriber descriptions are delimited by an open square bracket with  [^ square brackets] where the open bracket is followed by a '^' caret.

In CA comments are put in ((double parentheses)).

chat2calite should convert all [^ descriptions]  into ((descriptions))

There is a sample  [^ description] on line 116 of the sample file

**Comment by mumair01** [comment]
Just to clarify, this caret is the circumflex accent (u+005E) right?

**Comment by saulalbert** [comment]
Yes ^ - it's U+005E : CIRCUMFLEX ACCENT
you can copy and paste the characters in the issues into http://www.babelstone.co.uk/Unicode/whatisit.html to check
